

--- Main Tables for User Management
CREATE TABLE IBMOB100.DASHBOARDUSER( 
	user_id INT GENERATED ALWAYS AS IDENTITY,
	USERNAME VARCHAR(45) CCSID 37 DEFAULT NULL , 
	"PASSWORD" VARCHAR(60) CCSID 37 DEFAULT NULL , 
	FIRSTNAME VARCHAR(45) CCSID 37 DEFAULT NULL , 
	LASTNAME VARCHAR(45) CCSID 37 DEFAULT NULL , 
	EMAIL VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ENABLED INTEGER NOT NULL DEFAULT 1 , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	ISERIESNAME FOR COLUMN ISERI00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ACCOUNTNONLOCKED FOR COLUMN ACCOU00001 INTEGER NOT NULL DEFAULT 1 , 
	ACCOUNTNONEXPIRED FOR COLUMN ACCOU00002 INTEGER NOT NULL DEFAULT 1 , 
	RESETTOKEN VARCHAR(60) CCSID 37 DEFAULT NULL , 
	RESETEXPIRY FOR COLUMN RESET00001 TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( USER_ID ) );    
  
CREATE TABLE IBMOB100.DASHBOARDROLE( 
	role_id INT GENERATED ALWAYS AS IDENTITY, 
	ROLE_NAME VARCHAR(45) CCSID 37 NOT NULL , 
	USER_ID INTEGER NOT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( ROLE_ID ) );
  
ALTER TABLE IBMOB100.DASHBOARDROLE 
	ADD CONSTRAINT IBMOB100."fk_roles_users" 
	FOREIGN KEY( USER_ID ) 
	REFERENCES IBMOB100.DASHBOARDUSER ( USER_ID ) 
	ON DELETE NO ACTION 
	ON UPDATE RESTRICT ; 

CREATE TABLE IBMOB100.DASHBOARDLOG ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY, 
	TABLE_ID INTEGER NOT NULL , 
	TABLE_NAME VARCHAR(60) CCSID 37 NOT NULL , 
	DESCRIPTION FOR COLUMN DESCR00001 VARCHAR(200) CCSID 37 DEFAULT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );
	
CREATE TABLE IBMOB100.DASHBOARDUPLOAD ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY, 
	TABLE_ID INTEGER NOT NULL , 
	TABLE_NAME VARCHAR(60) CCSID 37 NOT NULL , 
	DESCRIPTION FOR COLUMN DESCR00001 VARCHAR(200) CCSID 37 DEFAULT NULL , 
	FILENAME VARCHAR(60) CCSID 37 DEFAULT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );
	

CREATE TABLE IBMOB100.DASHBOARDCOMMENT ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY, 
	TABLE_ID INTEGER NOT NULL , 
	TABLE_NAME VARCHAR(60) CCSID 37 NOT NULL , 
	DESCRIPTION FOR COLUMN DESCR00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	MESSAGE VARCHAR(1000) CCSID 37 DEFAULT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );
	
CREATE TABLE IBMOB100.USER_ATTEMPT ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,  
	USERNAME VARCHAR(45) CCSID 37 NOT NULL , 
	ATTEMPT INTEGER NOT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );   

CREATE TABLE IBMOB100.USER_PASSWORD ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,  
	USERNAME VARCHAR(45) CCSID 37 NOT NULL , 
	"PASSWORD" VARCHAR(60) CCSID 37 DEFAULT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );   



-- Tables for REST Oauth2.0
CREATE TABLE IBMOB100.OAUTH_CLIENT_DETAILS ( 
	CLIENT_ID VARCHAR(100) CCSID 37 NOT NULL , 
	RESOURCE_IDS FOR COLUMN RESOU00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	CLIENT_SECRET FOR COLUMN CLIEN00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	SCOPE VARCHAR(100) CCSID 37 DEFAULT NULL , 
	AUTHORIZED_GRANT_TYPES FOR COLUMN AUTHO00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	WEB_SERVER_REDIRECT_URI FOR COLUMN WEB_S00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	AUTHORITIES FOR COLUMN AUTHO00002 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	ACCESS_TOKEN_VALIDITY FOR COLUMN ACCES00001 INTEGER DEFAULT NULL , 
	REFRESH_TOKEN_VALIDITY FOR COLUMN REFRE00001 INTEGER DEFAULT NULL , 
	ADDITIONAL_INFORMATION FOR COLUMN ADDIT00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	AUTOAPPROVE FOR COLUMN AUTOA00001 VARCHAR(100) CCSID 37 DEFAULT NULL , 
	PRIMARY KEY( CLIENT_ID ) );

CREATE TABLE IBMOB100.OAUTH_ACCESS_TOKEN ( 
	TOKEN_ID VARCHAR(256) CCSID 37 DEFAULT NULL , 
	TOKEN BLOB(1048576) DEFAULT NULL , 
	AUTHENTICATION_ID FOR COLUMN AUTHE00001 VARCHAR(256) CCSID 37 DEFAULT NULL , 
	USER_NAME VARCHAR(256) CCSID 37 DEFAULT NULL , 
	CLIENT_ID VARCHAR(256) CCSID 37 DEFAULT NULL , 
	AUTHENTICATION FOR COLUMN AUTHE00002 BLOB(1048576) DEFAULT NULL , 
	REFRESH_TOKEN FOR COLUMN REFRE00001 VARCHAR(256) CCSID 37 DEFAULT NULL );   
	
CREATE TABLE IBMOB100.OAUTH_REFRESH_TOKEN ( 
	TOKEN_ID VARCHAR(256) CCSID 37 DEFAULT NULL , 
	TOKEN BLOB(1048576) DEFAULT NULL , 
	AUTHENTICATION FOR COLUMN AUTHE00001 BLOB(1048576) DEFAULT NULL );   

--- Tables for KYC approval and disapproval
CREATE TABLE IBMOB100.AMLBATCHREQUEST ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,   
	NAME VARCHAR(70) CCSID 37 DEFAULT NULL , 
	DESCRIPTION FOR COLUMN DESCR00001 VARCHAR(200) CCSID 37 DEFAULT NULL , 
	REQUESTID VARCHAR(45) CCSID 37 NOT NULL , 
	TRANSACTIONTYPE FOR COLUMN TRANS00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	BANKSCHEMA VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );   

CREATE TABLE IBMOB100.AMLBATCHCIF ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,   
	REQUESTID VARCHAR(45) CCSID 37 NOT NULL , 
	TRANSACTIONTYPE FOR COLUMN TRANS00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CIFREFERENCE FOR COLUMN CIFRE00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	AUDITDESCRIPTION FOR COLUMN AUDIT00001 VARCHAR(200) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(45) CCSID 37 DEFAULT NULL , 
	AMLBATCHREQUEST_ID FOR COLUMN AMLBA00001 INTEGER NOT NULL , 
	CREATEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	CREATEDON TIMESTAMP DEFAULT NULL , 
	MODIFIEDBY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	MODIFIEDON TIMESTAMP DEFAULT NULL , 
	ISERIESNAME FOR COLUMN ISERI00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );  
	
ALTER TABLE IBMOB100.AMLBATCHCIF 
	ADD CONSTRAINT IBMOB100."fk_container_request" 
	FOREIGN KEY( AMLBATCHREQUEST_ID ) 
	REFERENCES IBMOB100.AMLBATCHREQUEST ( "ID" ) 
	ON DELETE NO ACTION 
	ON UPDATE RESTRICT ; 

CREATE TABLE IBMOB100.AMLBATCHREVERSAL ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,   
	REQUESTID VARCHAR(45) CCSID 37 NOT NULL , 
	CIFREFERENCE FOR COLUMN CIFRE00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	FLAGAPPROVAL FOR COLUMN FLAGA00001 CHAR(5) CCSID 37 NOT NULL , 
	UPDATEDONAML FOR COLUMN UPDAT00001 DATE DEFAULT NULL , 
	BATCHUPDATEDONAML FOR COLUMN BATCH00001 TIME DEFAULT NULL , 
	UPDATEDBYAML FOR COLUMN UPDAT00002 CHAR(15) CCSID 37 NOT NULL , 
	CREATEDON TIME DEFAULT NULL , 
	ISERIESNAME FOR COLUMN ISERI00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );   
  
  
  -- Table for W-8-BENE Form
  CREATE TABLE IBMOB100.W8BENEFORM ( 
	"ID" INT GENERATED ALWAYS AS IDENTITY,  
	CIF VARCHAR(45) CCSID 37 DEFAULT NULL , 
	NAME VARCHAR(500) CCSID 37 DEFAULT NULL , 
	PHYSICALCOUNTRYINC FOR COLUMN PHYSI00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PHYSICALADDRESS FOR COLUMN PHYSI00002 VARCHAR(500) CCSID 37 DEFAULT NULL , 
	PHYSICALCITY FOR COLUMN PHYSI00003 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PHYSICALCOUNTRY FOR COLUMN PHYSI00004 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ALTADDRESS VARCHAR(500) CCSID 37 DEFAULT NULL , 
	ALTCITY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ALTCOUNTRY VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ACCOUNT VARCHAR(45) CCSID 37 DEFAULT NULL , 
	LABELNAME VARCHAR(200) CCSID 37 DEFAULT NULL , 
	OFFICER VARCHAR(45) CCSID 37 DEFAULT NULL , 
	BRANCH VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ALTADDRESSLABEL FOR COLUMN ALTAD00001 VARCHAR(500) CCSID 37 DEFAULT NULL , 
	ALTCITYLABEL FOR COLUMN ALTCI00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	ALTCOUNTRYLABEL FOR COLUMN ALTCO00001 VARCHAR(45) CCSID 37 DEFAULT NULL , 
	PRIMARY KEY( "ID" ) );   
	
	
	
-- Used for Dropping of Core Tables	
DROP TABLE IBMOB100.DASHBOARDROLE;
DROP TABLE IBMOB100.DASHBOARDUSER;
DROP TABLE IBMOB100.DASHBOARDLOG;
DROP TABLE IBMOB100.DASHBOARDUPLOAD;
DROP TABLE IBMOB100.DASHBOARDCOMMENT;
DROP TABLE IBMOB100.USER_ATTEMPT;
DROP TABLE IBMOB100.USER_PASSWORD;
DROP TABLE IBMOB100.OAUTH_CLIENT_DETAILS;
DROP TABLE IBMOB100.OAUTH_ACCESS_TOKEN;
DROP TABLE IBMOB100.OAUTH_REFRESH_TOKEN;
DROP TABLE IBMOB100.AMLBATCHCIF;
DROP TABLE IBMOB100.AMLBATCHREQUEST;
DROP TABLE IBMOB100.AMLBATCHREVERSAL;
DROP TABLE IBMOB100.W8BENEFORM;


INSERT INTO IBMOB100.DashboardUser (username, password, firstname, lastname, email, createdon, modifiedon) VALUES (
	'nell'
	,'medina'
	,'Marinell'
	,'Medina'
	,'medinama@ph.ibm.com'
	, CURRENT TIMESTAMP
	, CURRENT TIMESTAMP
); 
INSERT INTO IBMOB100.DashboardRole (role_name, user_id) VALUES ('Administrator', 1);

INSERT INTO IBMOB100.oauth_client_details(client_id, resource_ids, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity)
VALUES ('oceandev', 'rest_api', '$2a$11$rkoH2xGwJHpWm3/dffocK.bRmYdmgko3C9h8wZpd0qwRw.uhuQSnq', 'trust,read,write', 'client_credentials,authorization_code,implicit,password,refresh_token', 'ROLE_DEV', '518400000', '5184000000');
INSERT INTO IBMOB100.oauth_client_details(client_id, resource_ids, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity)
VALUES ('oceantest', 'rest_api', '$2a$11$Xs.L9mHog2fzBl83nz.Zg.9c8xtdknKzNj4h3CrkKuO9VifggM1am', 'trust,read,write', 'client_credentials,authorization_code,implicit,password,refresh_token', 'ROLE_TEST', '518400000', '5184000000');


/**
 * Sample Oauth2 request and refresh token	
 * 
 * request a token with refresh token
 * http://localhost:8085/restoauth-webapp-oceanbank/oauth/token?grant_type=password&client_id=oceandev&client_secret=ocean@123&username=oceandev&password=ocean@123
 * 
 * refresh a token
 * http://localhost:8085/restoauth-webapp-oceanbank/oauth/token?grant_type=refresh_token&client_id=oceandev&client_secret=ocean@123&refresh_token=a6a8207c-40ed-4a5d-b9e9-1951397d76ff
 * 
 */

